
services:
  app:
    image: worlddb
    container_name: world_app
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306



